### ISSUE TITLE
docker volumes not defined in the docker-compose

### ISSUE THREAD

**Issue by Oriun** [Oriun/doctor-compose#18]
The following doesn't work

```yml
version: "3.9"
services:
    doctor-postgresql:
        # PostgreSQL database service
        image: postgres:15-alpine
        volumes:
            - postgresql.db:/var/lib/postgresql/data
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: doctor-postgres
            POSTGRES_PASSWORD: AB19azAQfCO8Kf8r
            POSTGRES_USER: mxnwuuM922Ecgykj
```

While the following works

```yml
version: "3.9"
services:
    doctor-postgresql:
        # PostgreSQL database service
        image: postgres:15-alpine
        volumes:
            - postgresql.db:/var/lib/postgresql/data
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: doctor-postgres
            POSTGRES_PASSWORD: AB19azAQfCO8Kf8r
            POSTGRES_USER: mxnwuuM922Ecgykj
volumes:
    postgresql.db:
```
